
services:
  mysql:
    image: mysql:8.0 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE} 
      MYSQL_PASSWORD: ${DB_PASSWORD} 